[tools]
node = '22'
python = '3.13'

[tasks.ecr-login]
description = "Docker login to an AWS ECR"
run = '''
#!/usr/bin/env bash
aws ecr get-login-password --region {{option(name='region', default='us-east-2')}} \
	| docker login --username AWS --password-stdin \
	$(aws sts get-caller-identity | jq -r .Account).dkr.ecr.{{option(name='region', default='us-east-2')}}.amazonaws.com
'''
