[tools]
node = '22'
python = '3.13'

[tasks.quick-push]
description = "Run this to quickly ammend and push to a git repo"
run = 'git commit --amend --no-edit --quiet && git push --force-with-lease --quiet && echo "Done"'

[tasks.ecr-login]
description = "Docker login to an AWS ECR"
run = '''
#!/usr/bin/env bash
aws ecr get-login-password --region {{option(name='region', default='us-east-2')}} \
	| docker login --username AWS --password-stdin \
	$(aws sts get-caller-identity | jq -r .Account).dkr.ecr.{{option(name='region', default='us-east-2')}}.amazonaws.com
'''
